DROP TYPE TY_TRALIX_ENVIOFAC_RESPONSE;
DROP TYPE TY_TRALIX_FACTURA;
DROP TYPE TY_TRALIX_LINEA_99;
DROP TYPE TY_TRALIX_LINEA_09;
DROP TYPE TY_TRALIX_ARR_07;
DROP TYPE TY_TRALIX_LINEA_07;
DROP TYPE TY_TRALIX_ARR_06;
DROP TYPE TY_TRALIX_LINEA_06;
DROP TYPE TY_TRALIX_ARR_05C;
DROP TYPE TY_TRALIX_LINEA_05C;
DROP TYPE TY_TRALIX_ARR_05;
DROP TYPE TY_TRALIX_LINEA_05;
DROP TYPE TY_TRALIX_LINEA_03;
DROP TYPE TY_TRALIX_LINEA_02A;
DROP TYPE TY_TRALIX_LINEA_02;
DROP TYPE TY_TRALIX_LINEA_01;
DROP TYPE TY_TRALIX_LINEA_00;

DROP TYPE TY_TRALIX_TSTA_ARR;
DROP TYPE TY_TRALIX_TSTA_OBJ;
DROP TYPE TY_TRALIX_REGTSTA;

DROP TYPE TY_TRALIX_COMPPAGO;
DROP TYPE TY_TRALIX_ARR_IMP_CP;
DROP TYPE TY_TRALIX_LINEA_IMP_CP;
DROP TYPE TY_TRALIX_LINEA_COMPDOCTREL;
DROP TYPE TY_TRALIX_LINEA_COMPTOT;
DROP TYPE TY_TRALIX_LINEA_COMPPAGOS;