--- 

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('MICROSERV', 'INTG_IPADE', '', '', 2, 
'INTEGR_TX', 'direccion de microservicio', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'https://mstest.ipade.mx', 'Integración Tralix');

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('MICROSERV', 'INTG_IPADE', '', '', 3, 
'WALLET_P', 'password de wallet', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'Ipade2025#$', 'Integración Tralix');

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('MICROSERV', 'INTG_IPADE', '', '', 4, 
'WALLET_L', 'ruta de wallet', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '/opt/oracle/dcs/commonstore/wallets/DBTEST_vtq_qro/cert', 'Integración Tralix');

-----------------

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_EMP', '', '', 1, 
'IPADE1', 'GUID de Empresa', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '6dfcc2bf-734f-4b36-961c-a23f62569870', 'Integración Tralix');

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_EMP', '', '', 2, 
'IPADE2', 'GUID de Empresa', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '472529fa-1b6a-42b5-bb99-15f19feff522', 'Integración Tralix');

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_CFD', '', '', 1, 
'IPADE1', 'GUID de UsoCFD', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'd67da01f379a3f1497e9a58f035d9697', 'Integración Tralix');

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_CFD', '', '', 2, 
'IPADE2', 'GUID de UsoCFD', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '585087f1c503fff95e94fdebe7ace250', 'Integración Tralix');

INSERT INTO GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'DESP_PROG', '', '', 2, 
'COD_DESP', 'Códigos de detalle', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'ALIM,COV1,COV2,DIP1,DIP2,DSEP,ESTS,EXAM,JOIN,RMAS,RPER,SC01,SC02,SEID,SEIN,TR01,TR02,VCL2,VCOL,VHB2,VHBS,VKM2,VKSM,VLB2,VLBS,VMIT,VMT2', 'Integración Tralix');

--- Menú de tipos de cobro para Tralix

INSERT INTO GZVPRMH
(GZVPRMH_CODE, GZVPRMH_DESC, GZVPRMH_CREATE_DATE, GZVPRMH_ACTIVITY_DATE, GZVPRMH_USER_ID, 
GZVPRMH_DATA_ORIGIN)
VALUES('FACTPAYLINEA', 'Tipos de pago para facturar en pago en línea', SYSDATE, SYSDATE, USER, 
'Carga Inicial');

DECLARE
    secuencial NUMBER;
    header_grupo gzvprmh.gzvprmh_code%TYPE := 'FACTPAYLINEA';
BEGIN
    FOR i IN (
        SELECT '04' as codigo, 'Tarjeta de Crédito' as descripcion FROM dual
        UNION
        SELECT '28' as codigo, 'Tarjeta de Débito' as descripcion FROM dual
    ) LOOP
        SELECT NVL(MAX(gzvprmd_seq_no), 0) + 1
        INTO secuencial
        FROM GZVPRMD
        WHERE gzvprmd_prmh_code = header_grupo
            AND gzvprmd_internal_code = i.codigo;
        
        INSERT INTO GZVPRMD (
            GZVPRMD_PRMH_CODE, GZVPRMD_SEQ_NO, GZVPRMD_INTERNAL_CODE, GZVPRMD_SHORT_EXTERNAL, GZVPRMD_EXTERNAL_CODE, 
            GZVPRMD_COMMENTS, GZVPRMD_CREATE_DATE, GZVPRMD_ACTIVITY_DATE, GZVPRMD_USER_ID, GZVPRMD_DATA_ORIGIN
        ) VALUES (
            header_grupo, secuencial, i.codigo, i.descripcion, '', 
            i.descripcion, SYSDATE, SYSDATE, USER, 'Carga Inicial');
    END LOOP;
        
    COMMIT;
END;

-- Datos para TVTSTA de notas de crédito
MERGE INTO TVVSDOC tgt
    USING (
        SELECT 'NDC' as TVVSDOC_CODE,
            'Notas de Crédito' as TVVSDOC_DESC,
            'Y' as TVVSDOC_INC_TAX,
            'A' as TVVSDOC_GMODE,
            'Y' as TVVSDOC_PREFIX1_IND,
            'N' as TVVSDOC_PREFIX2_IND,
            USER as TVVSDOC_USER_ID,
            'Carga_Inicial' as TVVSDOC_DATA_ORIGIN
        FROM dual
    ) src
    ON (tgt.TVVSDOC_CODE=src.TVVSDOC_CODE)
    WHEN MATCHED
    THEN UPDATE SET
        tgt.TVVSDOC_DESC=src.TVVSDOC_DESC, 
        tgt.TVVSDOC_INC_TAX=src.TVVSDOC_INC_TAX, 
        tgt.TVVSDOC_GMODE=src.TVVSDOC_GMODE, 
        tgt.TVVSDOC_PREFIX1_IND=src.TVVSDOC_PREFIX1_IND, 
        tgt.TVVSDOC_PREFIX2_IND=src.TVVSDOC_PREFIX2_IND, 
        tgt.TVVSDOC_ACTIVITY_DATE=SYSDATE, tgt.TVVSDOC_USER_ID=src.TVVSDOC_USER_ID, 
        tgt.TVVSDOC_DATA_ORIGIN=src.TVVSDOC_DATA_ORIGIN
    WHEN NOT MATCHED
    THEN INSERT (TVVSDOC_CODE, TVVSDOC_DESC, TVVSDOC_INC_TAX, TVVSDOC_GMODE, TVVSDOC_PREFIX1_IND, 
        TVVSDOC_PREFIX2_IND, TVVSDOC_ACTIVITY_DATE, TVVSDOC_USER_ID, TVVSDOC_DATA_ORIGIN)
    VALUES (src.TVVSDOC_CODE, src.TVVSDOC_DESC, src.TVVSDOC_INC_TAX, src.TVVSDOC_GMODE, src.TVVSDOC_PREFIX1_IND, 
        src.TVVSDOC_PREFIX2_IND, SYSDATE, src.TVVSDOC_USER_ID, src.TVVSDOC_DATA_ORIGIN);

MERGE INTO TVRSDSQ tgt
    USING (SELECT 'NDC' as TVRSDSQ_SDOC_CODE,
        'FACTURACION' as TVRSDSQ_FBPR_CODE,
        1 as TVRSDSQ_SEQ_NUM,
        1 as TVRSDSQ_MAX_SEQ,
        1 as TVRSDSQ_INIT_SEQ,
        9999999 as TVRSDSQ_FINAL_SEQ,
        TO_DATE('31-12-2099', 'DD-MM-YYYY') as TVRSDSQ_VALID_UNTIL,
        SYSDATE as TVRSDSQ_ACTIVITY_DATE,
        USER as TVRSDSQ_USER_ID,
        'Carga Inicial' as TVRSDSQ_DATA_ORIGIN 
        FROM dual) src
    ON (tgt.TVRSDSQ_SDOC_CODE = src.TVRSDSQ_SDOC_CODE
        AND tgt.TVRSDSQ_FBPR_CODE = src.TVRSDSQ_FBPR_CODE
        AND tgt.TVRSDSQ_SEQ_NUM = src.TVRSDSQ_SEQ_NUM)
    WHEN MATCHED
    THEN UPDATE SET
        tgt.TVRSDSQ_MAX_SEQ=src.TVRSDSQ_MAX_SEQ, 
        tgt.TVRSDSQ_INIT_SEQ=src.TVRSDSQ_INIT_SEQ, 
        tgt.TVRSDSQ_FINAL_SEQ=src.TVRSDSQ_FINAL_SEQ, 
        tgt.TVRSDSQ_VALID_UNTIL=src.TVRSDSQ_VALID_UNTIL, 
        tgt.TVRSDSQ_ACTIVITY_DATE=src.TVRSDSQ_ACTIVITY_DATE, 
        tgt.TVRSDSQ_USER_ID=src.TVRSDSQ_USER_ID, 
        tgt.TVRSDSQ_DATA_ORIGIN=src.TVRSDSQ_DATA_ORIGIN
    WHEN NOT MATCHED
    THEN INSERT (TVRSDSQ_SDOC_CODE, TVRSDSQ_FBPR_CODE, TVRSDSQ_SEQ_NUM, TVRSDSQ_MAX_SEQ,
        TVRSDSQ_INIT_SEQ, TVRSDSQ_FINAL_SEQ, TVRSDSQ_VALID_UNTIL, TVRSDSQ_ACTIVITY_DATE, 
        TVRSDSQ_USER_ID, TVRSDSQ_DATA_ORIGIN)
    VALUES (src.TVRSDSQ_SDOC_CODE, src.TVRSDSQ_FBPR_CODE, src.TVRSDSQ_SEQ_NUM, src.TVRSDSQ_MAX_SEQ,
        src.TVRSDSQ_INIT_SEQ, src.TVRSDSQ_FINAL_SEQ, src.TVRSDSQ_VALID_UNTIL, src.TVRSDSQ_ACTIVITY_DATE, 
        src.TVRSDSQ_USER_ID, src.TVRSDSQ_DATA_ORIGIN);

COMMIT;