--- 

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('MICROSERV', 'INTG_IPADE', '', '', 2, 
'INTEGR_TX', 'direccion de microservicio', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'https://mstest.ipade.mx', 'Integración Tralix');

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('MICROSERV', 'INTG_IPADE', '', '', 3, 
'WALLET_P', 'password de wallet', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'Ipade2025#$', 'Integración Tralix');

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('MICROSERV', 'INTG_IPADE', '', '', 4, 
'WALLET_L', 'ruta de wallet', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '/opt/oracle/dcs/commonstore/wallets/DBTEST_vtq_qro/cert', 'Integración Tralix');

-----------------

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_EMP', '', '', 1, 
'IPADE1', 'GUID de Empresa', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '6dfcc2bf-734f-4b36-961c-a23f62569870', 'Integración Tralix');

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_EMP', '', '', 2, 
'IPADE2', 'GUID de Empresa', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '472529fa-1b6a-42b5-bb99-15f19feff522', 'Integración Tralix');

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_CFD', '', '', 1, 
'IPADE1', 'GUID de UsoCFD', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'd67da01f379a3f1497e9a58f035d9697', 'Integración Tralix');

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'TRALIX_CFD', '', '', 2, 
'IPADE2', 'GUID de UsoCFD', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', '585087f1c503fff95e94fdebe7ace250', 'Integración Tralix');

INSERT INTO "GENERAL".GTVSDAX
(GTVSDAX_EXTERNAL_CODE, GTVSDAX_INTERNAL_CODE, GTVSDAX_REPORTING_DATE, GTVSDAX_TRANSLATION_CODE, GTVSDAX_INTERNAL_CODE_SEQNO, 
GTVSDAX_INTERNAL_CODE_GROUP, GTVSDAX_DESC, GTVSDAX_SYSREQ_IND, GTVSDAX_ACTIVITY_DATE, GTVSDAX_USER_ID, 
GTVSDAX_SYSI_CODE, GTVSDAX_CONCEPT, GTVSDAX_COMMENTS, GTVSDAX_DATA_ORIGIN)
VALUES('TRALIX_FACT', 'DESP_PROG', '', '', 2, 
'COD_DESP', 'Códigos de detalle', '', SYSDATE, 'ECTOTEC_USER', 
'S', 'microservicio', 'ALIM,COV1,COV2,DIP1,DIP2,DSEP,ESTS,EXAM,JOIN,RMAS,RPER,SC01,SC02,SEID,SEIN,TR01,TR02,VCL2,VCOL,VHB2,VHBS,VKM2,VKSM,VLB2,VLBS,VMIT,VMT2', 'Integración Tralix');

--- Menú de tipos de cobro para Tralix

INSERT INTO "GENERAL".GZVPRMH
(GZVPRMH_CODE, GZVPRMH_DESC, GZVPRMH_CREATE_DATE, GZVPRMH_ACTIVITY_DATE, GZVPRMH_USER_ID, 
GZVPRMH_DATA_ORIGIN)
VALUES('FACTPAYLINEA', 'Tipos de pago para facturar en pago en línea', SYSDATE, SYSDATE, USER, 
'Carga Inicial');

DECLARE
    secuencial NUMBER;
    header_grupo gzvprmh.gzvprmh_code%TYPE := 'FACTPAYLINEA';
BEGIN
    FOR i IN (
        SELECT '04' as codigo, 'Tarjeta de Crédito' as descripcion FROM dual
        UNION
        SELECT '28' as codigo, 'Tarjeta de Débito' as descripcion FROM dual
    ) LOOP
        SELECT NVL(MAX(gzvprmd_seq_no), 0) + 1
        INTO secuencial
        FROM GZVPRMD
        WHERE gzvprmd_prmh_code = header_grupo
            AND gzvprmd_internal_code = i.codigo;
        
        INSERT INTO "GENERAL".GZVPRMD (
            GZVPRMD_PRMH_CODE, GZVPRMD_SEQ_NO, GZVPRMD_INTERNAL_CODE, GZVPRMD_SHORT_EXTERNAL, GZVPRMD_EXTERNAL_CODE, 
            GZVPRMD_COMMENTS, GZVPRMD_CREATE_DATE, GZVPRMD_ACTIVITY_DATE, GZVPRMD_USER_ID, GZVPRMD_DATA_ORIGIN
        ) VALUES (
            header_grupo, secuencial, i.codigo, i.descripcion, '', 
            i.descripcion, SYSDATE, SYSDATE, USER, 'Carga Inicial');
    END LOOP;
        
    COMMIT;
END;

COMMIT;