-- Conectado como BANINST1

GRANT EXECUTE ON F_FORMAT_NAME TO IPADEDEV;

GRANT EXECUTE ON GOKJSON TO IPADEDEV;

GRANT EXECUTE ON SB_CURRICULUM_STR TO IPADEDEV;

GRANT EXECUTE ON GB_COMMON TO IPADEDEV;

GRANT INSERT, UPDATE, REFERENCES ON tvrpays TO ipadedev;

GRANT INSERT, REFERENCES ON tzrpofi TO ipadedev;

GRANT INSERT, REFERENCES, SELECT, UPDATE ON tvrtsta TO ipadedev;